(async()=>{
 const $=id=>document.getElementById(id),isExtension=!!globalThis.chrome?.runtime?.id;
 let demoSettings=XL.defaults(),demoOverrides={},demoProfiles=[];
 const api=async msg=>{if(isExtension)return chrome.runtime.sendMessage(msg);if(msg.type==='init')return {settings:demoSettings,cache:{},overrides:demoOverrides,profiles:demoProfiles};if(msg.type==='save'||msg.type==='import'){demoSettings=XL.cleanSettings(msg.settings);if(msg.overrides)demoOverrides=XL.cleanOverrides(msg.overrides);return {settings:demoSettings,overrides:demoOverrides};}if(msg.type==='pause'){demoSettings.pauseUntil=msg.minutes?Date.now()+msg.minutes*60000:0;return {settings:demoSettings};}if(msg.type==='profile'){if(msg.action==='save'){const same=demoProfiles.find(p=>p.name===msg.name);demoProfiles=demoProfiles.filter(p=>p.id!==same?.id).concat({id:same?.id||crypto.randomUUID(),name:msg.name,settings:structuredClone(demoSettings)});}if(msg.action==='delete')demoProfiles=demoProfiles.filter(p=>p.id!==msg.id);if(msg.action==='apply'){const profile=demoProfiles.find(p=>p.id===msg.id);if(profile)demoSettings=structuredClone(profile.settings);}return {profiles:demoProfiles,settings:demoSettings};}if(msg.type==='override'){if(msg.code===null)delete demoOverrides[msg.handle];else demoOverrides[msg.handle]={code:msg.code,checked:Date.now()};return {overrides:demoOverrides};}return {};};
 let init=await api({type:'init'}),settings=XL.cleanSettings(init.settings),overrides=XL.cleanOverrides(init.overrides),profiles=XL.cleanProfiles(init.profiles),previous=null,selectedOnly=false,toastTimer,saveChain=Promise.resolve();const nodes=new Map(),rows=new Map();
 if(!isExtension)$('preview').hidden=false;
 const toast=t=>{$('toast').textContent=t;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2400);};
 function persist(message='Saved on this laptop'){const snapshot=structuredClone(settings);saveChain=saveChain.then(()=>api({type:'save',settings:snapshot})).then(r=>{if(r.error)throw Error(r.error);toast(isExtension?message:'Preview updated · not applied to X');salute();}).catch(e=>toast('Could not save: '+e.message));}
 function change(fn){previous=structuredClone(settings);fn();paint();persist();}
 function toggle(code){change(()=>{const set=new Set(settings.blocked);set.has(code)?set.delete(code):set.add(code);settings.blocked=[...set];});pulse(code);}
 function pulse(code){const n=nodes.get(code);if(!n||!settings.motion||matchMedia('(prefers-reduced-motion: reduce)').matches)return;n.getAnimations().forEach(a=>a.cancel());n.animate([{fill:'#ffffff'}, {fill:settings.blocked.includes(code)?'#72def6':'#29485e'}],{duration:500,easing:'ease-out'});}
 function make(tag,text,cls){const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;}
 const ns='http://www.w3.org/2000/svg';const group=document.createElementNS(ns,'g');$('map').append(group);
 for(const c of XL.countries){let n;if(XLMap[c.code]){n=document.createElementNS(ns,'path');n.setAttribute('d',XLMap[c.code]);}else{n=document.createElementNS(ns,'circle');n.setAttribute('cx',(c.latlng[1]+180)*2.5);n.setAttribute('cy',(90-c.latlng[0])*2.5);n.setAttribute('r','2.6');}
  n.dataset.code=c.code;n.setAttribute('role','button');n.setAttribute('tabindex','0');n.setAttribute('aria-label',c.name);const title=document.createElementNS(ns,'title');title.textContent=c.name;n.append(title);group.append(n);nodes.set(c.code,n);
  n.addEventListener('pointerenter',()=>{$('mapTooltip').textContent=`${c.name} · ${settings.blocked.includes(c.code)?'Filtered — click to show':'Shown — click to filter'}`;});
  n.addEventListener('click',()=>{if(!dragged)toggle(c.code);});n.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle(c.code);}});
  const label=make('label',null,'country-row'),input=make('input');input.type='checkbox';input.setAttribute('aria-label',`Filter ${c.name}`);input.addEventListener('change',()=>toggle(c.code));label.append(input,make('span',XL.flag(c.iso2),'flag'),make('span',c.name,'name'),make('span',c.code,'code'));$('countryList').append(label);rows.set(c.code,{label,input});
 }
 const regionButtons=[];const continents=['Africa','Asia','Europe','North America','South America','Oceania','Antarctica'];
 function regionButton(name,codes,target){const b=make('button',name);b.type='button';b.onclick=()=>change(()=>{const set=new Set(settings.blocked),all=codes.every(c=>set.has(c));codes.forEach(c=>all?set.delete(c):set.add(c));settings.blocked=[...set];});target.append(b);regionButtons.push({b,codes,name});}
 for(const r of continents)regionButton(r,XL.countries.filter(c=>c.region===r).map(c=>c.code),$('regions'));
 for(const r of [...new Set(XL.countries.map(c=>c.subregion).filter(r=>r&&!continents.includes(r)))].sort())regionButton(r,XL.countries.filter(c=>c.subregion===r).map(c=>c.code),$('subregions'));
 function paint(){const set=new Set(settings.blocked);$('total').textContent=set.size;$('selectedCount').textContent=set.size;$('undo').disabled=!previous;$('enabled').checked=settings.enabled;$('enabledLabel').textContent=settings.pauseUntil>Date.now()?'Timed pause':settings.enabled?'Filtering on':'Filtering paused';document.body.classList.toggle('paused',!settings.enabled);
  for(const id of ['mode','unknown','badge','regionPolicy'])$(id).value=settings[id];$('quotes').checked=settings.quotes;$('motion').checked=settings.motion;$('preserveReposts').checked=settings.preserveReposts;$('pauseStatus').textContent=settings.pauseUntil>Date.now()?'Resumes '+new Date(settings.pauseUntil).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'No timed pause';document.body.classList.toggle('still',!settings.motion);
  for(const c of XL.countries){const chosen=set.has(c.code),node=nodes.get(c.code);node.classList.toggle('selected',chosen);node.setAttribute('aria-pressed',String(chosen));node.setAttribute('aria-label',`${c.name}: ${chosen?'filtered':'shown'}`);rows.get(c.code).input.checked=chosen;}
  for(const {b,codes,name} of regionButtons){const count=codes.filter(c=>set.has(c)).length;b.setAttribute('aria-pressed',String(count===codes.length));b.classList.toggle('partial',count>0&&count<codes.length);b.title=`${name}: ${count} of ${codes.length} selected`;}
  $('sampleBadge').textContent=XL.badge({raw:'Australia'},settings.badge);filterList();
 }
 function filterList(){const q=XL.norm($('search').value);let count=0;for(const c of XL.countries){const visible=(!selectedOnly||settings.blocked.includes(c.code))&&(!q||[c.name,c.code,c.iso2,c.region,c.subregion,...c.aliases].some(n=>XL.norm(n).includes(q)));rows.get(c.code).label.hidden=!visible;if(visible)count++;}$('listCount').textContent=`${count} places · checked means filtered`;$('allTab').setAttribute('aria-pressed',String(!selectedOnly));$('selectedTab').setAttribute('aria-pressed',String(selectedOnly));}
 $('search').oninput=filterList;$('allTab').onclick=()=>{selectedOnly=false;filterList();};$('selectedTab').onclick=()=>{selectedOnly=true;filterList();};
 $('undo').onclick=()=>{if(previous){const old=settings;settings=previous;previous=old;paint();persist('Selection restored');}};$('clear').onclick=()=>change(()=>settings.blocked=[]);
 for(const id of ['mode','unknown','badge','regionPolicy'])$(id).onchange=()=>change(()=>settings[id]=$(id).value);
 for(const id of ['enabled','quotes','motion','preserveReposts'])$(id).onchange=()=>change(()=>{settings[id]=$(id).checked;if(id==='enabled')settings.pauseUntil=0;});
 $('allow').value=settings.allow.map(h=>'@'+h).join('\n');$('saveAllow').onclick=()=>{const parts=$('allow').value.split(/[\s,;]+/).filter(Boolean).map(h=>h.replace(/^@/,''));if(parts.some(h=>!/^[a-z0-9_]{1,15}$/i.test(h))){$('allowFeedback').textContent='Use valid X handles: letters, numbers and underscores, up to 15 characters.';return;}change(()=>settings.allow=[...new Set(parts.map(h=>h.toLowerCase()))]);$('allowFeedback').textContent=`${settings.allow.length} account exceptions saved.`;};
 $('cacheCount').textContent=Object.keys(init.cache||{}).length;$('clearCache').onclick=async()=>{await api({type:'clear'});$('cacheCount').textContent='0';toast('Location cache cleared');};
 $('export').onclick=()=>{const blob=new Blob([JSON.stringify({format:'brownout-settings',version:3,settings,overrides,profiles},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=make('a');a.href=url;a.download='brownout-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('import').onclick=()=>$('importFile').click();$('importFile').onchange=async()=>{try{const f=$('importFile').files[0];if(!f)return;if(f.size>1500000)throw Error('File is too large');const d=JSON.parse(await f.text());if(!(['atlas-settings','brownout-settings'].includes(d.format))||![1,2,3].includes(d.version)||!d.settings)throw Error('Choose a Brownout or Atlas settings export');await saveChain;const result=await api({type:'import',settings:d.settings,overrides:d.version>=2?d.overrides:undefined,profiles:d.version>=3?d.profiles:undefined});if(result.error)throw Error(result.error);previous=structuredClone(settings);settings=XL.cleanSettings(result.settings);overrides=XL.cleanOverrides(result.overrides||overrides);profiles=XL.cleanProfiles(result.profiles||profiles);paint();paintNotes();paintProfiles();toast('Settings and field notes imported');$('allow').value=settings.allow.map(h=>'@'+h).join('\n');}catch(e){toast(e.message);}$('importFile').value='';};
 let view={x:0,y:0,w:900,h:450},start,dragged=false;
 const setView=()=>$('map').setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);
 function zoom(f){const w=Math.max(150,Math.min(900,view.w*f)),h=w/2;view={x:view.x+(view.w-w)/2,y:view.y+(view.h-h)/2,w,h};setView();}
 $('zoomIn').onclick=()=>zoom(.7);$('zoomOut').onclick=()=>zoom(1/.7);$('resetMap').onclick=()=>{view={x:0,y:0,w:900,h:450};setView();};
 $('map').addEventListener('pointerdown',e=>{dragged=false;start={x:e.clientX,y:e.clientY,v:{...view}};});
 $('map').addEventListener('pointermove',e=>{if(!start||!e.buttons)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dx)+Math.abs(dy)>5){dragged=true;const scale=view.w/$('map').getBoundingClientRect().width;view.x=start.v.x-dx*scale;view.y=start.v.y-dy*scale;setView();}});
 window.addEventListener('pointerup',()=>{start=null;});
 async function connection(){if(!isExtension)return;const s=await chrome.storage.session.get(null),recent=Object.values(s).filter(v=>v&&Date.now()-v.time<20000).sort((a,b)=>b.time-a.time)[0];if(recent){$('connectionTitle').textContent=recent.ready?'Connected to X.':'Connecting to X…';$('connectionText').textContent=recent.text+` · ${recent.hidden} posts filtered in the latest active tab.`;$('queueHealth').textContent=`${recent.queued??recent.pending} queued in this tab · 200 maximum · off-screen entries dropped.`;}else{$('connectionTitle').textContent='Ready when you open X.';$('connectionText').textContent='Open or refresh an X tab to connect. Keep X visible while new locations are checked.';}}
 if(isExtension){chrome.storage.onChanged.addListener((changes,area)=>{if(area==='local'&&changes.cache)$('cacheCount').textContent=Object.keys(changes.cache.newValue||{}).length;if(area==='local'&&changes.profiles){profiles=XL.cleanProfiles(changes.profiles.newValue);paintProfiles();}if(area==='local'&&changes.settings){settings=XL.cleanSettings(changes.settings.newValue);paint();}if(area==='local'&&changes.overrides){overrides=XL.cleanOverrides(changes.overrides.newValue);paintNotes();}});setInterval(connection,5000);}
 function salute(){if(!settings.motion||matchMedia('(prefers-reduced-motion: reduce)').matches)return;$('knight').classList.remove('salute');void $('knight').offsetWidth;$('knight').classList.add('salute');}
 $('knight').onclick=()=>{salute();toast('At your service. A quiet feed awaits.');};
 function paintNotes(){const q=XL.norm($('noteSearch').value),entries=Object.entries(overrides).sort((a,b)=>a[0].localeCompare(b[0]));$('overrideCount').textContent=entries.length+' notes';$('overrideList').replaceChildren();let count=0;
 for(const [handle,o] of entries){const c=XL.byCode.get(o.code);if(q&&!XL.norm(handle+' '+c.name+' '+c.code).includes(q))continue;count++;const row=make('div',null,'note-row'),name=make('span','@'+handle),country=make('span',XL.flag(c.iso2)+' '+c.name+' · '+c.code),remove=make('button','Remove note','text-button');remove.setAttribute('aria-label','Remove manual location for @'+handle);remove.onclick=async()=>{const r=await api({type:'override',handle,code:null});if(r.error){toast(r.error);return;}overrides=XL.cleanOverrides(r.overrides);paintNotes();toast('Note removed · using X’s location again');};row.append(name,country,remove);$('overrideList').append(row);}
 if(!count)$('overrideList').append(make('p',q?'No matching field notes.':'Your ledger is empty. On X, click any location pill → choose a country → Save my location.','notes-empty'));}
 $('noteSearch').oninput=paintNotes;
 function paintProfiles(){const current=$('profileSelect').value;$('profileSelect').replaceChildren(new Option('Choose a profile',''));for(const p of profiles)$('profileSelect').append(new Option(p.name,p.id));if(profiles.some(p=>p.id===current))$('profileSelect').value=current;}
 async function profile(action){await saveChain;const name=$('profileName').value.trim(),id=$('profileSelect').value;if(action==='save'&&!name){toast('Give this setup a name first.');return;}if(action!=='save'&&!id){toast('Choose a profile first.');return;}const result=await api({type:'profile',action,name,id});if(result.error){toast(result.error);return;}profiles=XL.cleanProfiles(result.profiles);if(result.settings){settings=XL.cleanSettings(result.settings);$('allow').value=settings.allow.map(h=>'@'+h).join('\n');paint();}paintProfiles();$('profileStatus').textContent=action==='save'?'Profile saved. The same name replaces a previous version.':action==='apply'?'Profile applied. Personal notes and pause state were preserved.':'Profile deleted.';toast($('profileStatus').textContent);}
 $('profileSave').onclick=()=>profile('save');$('profileApply').onclick=()=>profile('apply');$('profileDelete').onclick=()=>profile('delete');
 async function pause(minutes){await saveChain;const result=await api({type:'pause',minutes});if(result.error){toast(result.error);return;}settings=XL.cleanSettings(result.settings);paint();toast(minutes?'Paused for 15 minutes':'Timed pause cleared');}
 $('pause15').onclick=()=>pause(15);$('resume').onclick=()=>pause(0);setInterval(()=>{if(settings.pauseUntil&&settings.pauseUntil<=Date.now()){settings.pauseUntil=0;paint();}},5000);
 paint();paintNotes();paintProfiles();connection();
})();
